Repository be15-beyondBBD/be15-1st-BeyondBBD-CultureRecord, pull requests merged in 2025-02, with the labels that each got.

#16 회원 기능 구현
  DML/UserBlock/MEM-13_delete_user_block.sql
  DML/UserBlock/MEM-14_get_user_block.sql
  DML/UserBlock/MEM-15_user_block.sql
  DML/UserFollow/MEM-23_follower_list.sql
  DML/UserFollow/MEM-24_following_list.sql
  DML/UserFollow/MEM-25_follow.sql
  DML/UserFollow/MEM-26_unfollow.sql
  DML/UserManagement/MEM-01_user_registration.sql
  DML/UserManagement/MEM-02_user_login.sql
  DML/UserManagement/MEM-03_modify_user_info.sql
  DML/UserManagement/MEM-04_find_user_id.sql
  DML/UserManagement/MEM-05_find_user_password.sql
  DML/UserManagement/MEM-06_delete_user.sql
  DML/UserMyPage/MEM-16_delete_user_interest.sql
  DML/UserMyPage/MEM-17_get_user_favorites.sql
  DML/UserMyPage/MEM-18_get_my_posts.sql
  DML/UserMyPage/MEM-19_insert_user_interest.sql
  DML/UserMyPage/MEM-20_get_bookmarked_posts.sql
  DML/UserMyPage/MEM-21_get_liked_posts.sql
  DML/UserMyPage/MEM-22_get_my_comment.sql
  DML/UserRecord/MEM-07_event_record_insert_request.sql
  DML/UserRecord/MEM-08_event_record_hide_setting.sql
  DML/UserRecord/MEM-09_get_event_record.sql
  DML/UserRecord/MEM-10_delete_event_record.sql
  DML/UserRecord/MEM-11-1_get_event_record_list.sql
  DML/UserRecord/MEM-11-2_get_event_record_list.sql
  DML/UserRecord/MEM-12_event_record_list_privacy_option_setting.sql
Labels: enhancement

#19 공연/전시 기능 구현
  DML/EventDetailView/PER-09_event_view_detail.sql
  DML/EventDetailView/PER-10_event_favorite_edit.sql
  DML/EventDetailView/PER-11_event_reserve_view.sql
  DML/EventView/PER-01_event_search.sql
  DML/EventView/PER-02_event_list_check.sql
  DML/EventView/PER-03_event_filter_field.sql
  DML/EventView/PER-04_event_filter_cast.sql
  DML/EventView/PER-05_event_filter_date.sql
  DML/EventView/PER-06_event_filter_location.sql
  DML/EventView/PER-07_event_filter_rating.sql
  DML/EventView/PER-08_event_filter_interest.sql
Labels: enhancement

#20 관리자 기능 구현
  DML/CommunityManagement/MAN-01_notice_insert.sql
  DML/CommunityManagement/MAN-02_notice_update.sql
  DML/CommunityManagement/MAN-03_notice_delete.sql
  DML/CommunityManagement/MAN-04_request_select.sql
  DML/CommunityManagement/MAN-05_request_accept.sql
  DML/CommunityManagement/MAN-06_request_reject.sql
  DML/ReportManagement/MAN-07_report_user.sql
  DML/ReportManagement/MAN-08_ban_user.sql
  DML/ReportManagement/MAN-09_report_post_delete.sql
  DML/ReportManagement/MAN-10 report_comment_delete.sql
Labels: enhancement

#21 게시판 기능 구현
  DML/Comment/BOA-10-1_insert_comment.sql
  DML/Comment/BOA-10-2_insert_parent_comment.sql
  DML/Comment/BOA-11_get_comment.sql
  DML/Comment/BOA-12_edit_comment.sql
  DML/Comment/BOA-13_delete_comment.sql
  DML/Comment/BOA-14_like_comment.sql
  DML/Comment/BOA-15_report_comment.sql
  DML/Post/BOA-01-01_post_searchby_nickname.sql
  DML/Post/BOA-01-02_post_searchby_title.sql
  DML/Post/BOA-02_post_list_view.sql
  DML/Post/BOA-03_post_view.sql
  DML/Post/BOA-04_post_report.sql
  DML/Post/BOA-05_post_insert.sql
  DML/Post/BOA-06_post_modify.sql
  DML/Post/BOA-07_post_delete.sql
  DML/Post/BOA-08_post_bookmark.sql
  DML/Post/BOA-09_post_like.sql
  DML/Review/BOA-16_insert_review.sql
Labels: enhancement

#25 게시판 기능 수정
  DML/Post/BOA-05_post_insert.sql
Labels: refactor

#26 관리자 기능 수정
  DML/CommunityManagement/MAN-01_notice_insert.sql
Labels: refactor

#17 트리거 기능 구현
  Trigger/TRI-01_deactivate_user_data.sql
  Trigger/TRI-02_ban_user_deactivate.sql
  Trigger/TRI-03_report_check_insert.sql
  Trigger/TRI-04_user_ban_check.sql
Labels: enhancement

#18 프로시저 기능 구현
  Procedure/PRO-01_create_post.sql
  Procedure/PRO-02_write_comment.sql
  Procedure/PRO-03_write_parent_comment.sql
  Procedure/PRO-04_view_comment.sql
  Procedure/PRO-05_edit_comment.sql
  Procedure/PRO-06_delete_comment.sql
  Procedure/PRO-07_view_event_record_list.sql
  Procedure/PRO-08_create_notice.sql
Labels: enhancement

#24 초기 데이터베이스 구성 구현
  DDL/DDL.sql
  DML/dummydata.sql
Labels: enhancement

#22 프로젝트 산출물 업로드
  Docs/최종산출물_ERD.png
  Docs/최종산출물_UML(유스케이스_다이어그램).png
  Docs/최종산출물_WBS.jpeg
  Docs/최종산출물_요구사항명세서.jpeg
  Docs/최종산출물_테이블정의서_1.jpg
  Docs/최종산출물_테이블정의서_2.jpg
Labels: documentation
